### ISSUE TITLE
Failed to load DoxyDoxygen (evolution)

### ISSUE THREAD

**Issue by jfcherng** [20Tauri/DoxyDoxygen#153]
Just updated to `Doxy​Doxygen (evolution)` `0.79.1` with ST 4099.

![image](https://user-images.githubusercontent.com/6594915/111818943-b4c69400-891a-11eb-9038-7ae0a768a738.png)

```
reloading python 3.3 plugin DoxyDoxygen (evolution).Doxy
from .doxy_libs.CrashReportHelpers import generate_report,send_report
Traceback (most recent call last):
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 137, in <module>
    "send_report",
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 129, in import_doxy_objects
    raise ex
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 126, in import_doxy_objects
    exec(source, globals())
  File "<string>", line 1, in <module>
ImportError: No module named 'DoxyDoxygen (evolution).doxy_libs'
error: DoxyDoxygen fails to import some files... Please restart SublimeText

(if problem persist please look at the console and send a report)
from .doxy_libs.SublimeHelpers import doxy_settings,log_debug
Traceback (most recent call last):
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 288, in <module>
    "log_debug",
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 129, in import_doxy_objects
    raise ex
  File "C:\Users\jfcherng\AppData\Roaming\Sublime Text\Installed Packages\DoxyDoxygen (evolution).sublime-package\Doxy.py", line 126, in import_doxy_objects
    exec(source, globals())
  File "<string>", line 1, in <module>
ImportError: No module named 'DoxyDoxygen (evolution).doxy_libs'
error: DoxyDoxygen fails to import some files... Please restart SublimeText

(if problem persist please look at the console and send a report)
```

---

Sorry but I have to sleep now :(

**Comment by 20Tauri** [comment]
Thanks for reporting
Problem occurs also with ST3 (ST2 version is OK).
I have temporary reverted package control to version 0.79.0.
Reinstall the plugin should solve the problem

**Comment by 20Tauri** [comment]
Compiled python files have a wrong extension. It is now fixed.
Once again thank you for reporting the issue so quickly

**Comment by jfcherng** [comment]
LGTM. Thanks!
